---
apiVersion: v1
kind: Service
metadata:
  name: mochalabs
  namespace: apps
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32410
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: sample
  sessionAffinity: None
  type: NodePort

